
package pwd.allen.jws.client;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsTestImplService", targetNamespace = "http://server.jws.allen.pwd/", wsdlLocation = "http://127.0.0.1:8090/service/WsTest?wsdl")
public class WsTestImplService
    extends Service
{

    private final static URL WSTESTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTESTIMPLSERVICE_EXCEPTION;
    private final static QName WSTESTIMPLSERVICE_QNAME = new QName("http://server.jws.allen.pwd/", "WsTestImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8090/service/WsTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTESTIMPLSERVICE_WSDL_LOCATION = url;
        WSTESTIMPLSERVICE_EXCEPTION = e;
    }

    public WsTestImplService() {
        super(__getWsdlLocation(), WSTESTIMPLSERVICE_QNAME);
    }

    public WsTestImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTESTIMPLSERVICE_QNAME, features);
    }

    public WsTestImplService(URL wsdlLocation) {
        super(wsdlLocation, WSTESTIMPLSERVICE_QNAME);
    }

    public WsTestImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTESTIMPLSERVICE_QNAME, features);
    }

    public WsTestImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsTestImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsTest
     */
    @WebEndpoint(name = "WsTestImplPort")
    public WsTest getWsTestImplPort() {
        return super.getPort(new QName("http://server.jws.allen.pwd/", "WsTestImplPort"), WsTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsTest
     */
    @WebEndpoint(name = "WsTestImplPort")
    public WsTest getWsTestImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.jws.allen.pwd/", "WsTestImplPort"), WsTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTESTIMPLSERVICE_EXCEPTION!= null) {
            throw WSTESTIMPLSERVICE_EXCEPTION;
        }
        return WSTESTIMPLSERVICE_WSDL_LOCATION;
    }

}
